-- Rivalta sul Mincio - complete Supabase bootstrap
-- Run this once in the Supabase SQL editor for a fresh setup.
-- It creates the base schema used by the site, the support tables,
-- RLS policies, moderation guards, and the optional categories catalog.
--
-- Note: if you want to upload real images to Supabase Storage,
-- create the public bucket `post-images` separately from the Storage UI.

create extension if not exists pgcrypto;

-- ------------------------------------------------------------------
-- Base tables expected by the frontend
-- ------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  display_name text not null,
  bio text,
  comune text,
  avatar_emoji text,
  avatar_color text,
  role text not null default 'user' check (role in ('admin', 'user', 'reader')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists username text,
  add column if not exists display_name text,
  add column if not exists bio text,
  add column if not exists comune text,
  add column if not exists avatar_emoji text,
  add column if not exists avatar_color text,
  add column if not exists role text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.profiles
set role = case
  when nullif(trim(coalesce(role, '')), '') is not null then role
  when comune = 'Fuori comune' then 'reader'
  else 'user'
end
where role is null or trim(role) = '';

update public.profiles
set created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now())
where created_at is null or updated_at is null;

create unique index if not exists idx_profiles_username_unique
  on public.profiles (lower(username));

create index if not exists idx_profiles_role
  on public.profiles (role);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  author_username text,
  title text not null,
  excerpt text,
  content text not null,
  category text not null default 'Territorio',
  badge text,
  badge_color text not null default 'default',
  image_type text,
  image_url text,
  source_url text,
  event_date timestamptz,
  published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.posts
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists author_username text,
  add column if not exists title text,
  add column if not exists excerpt text,
  add column if not exists content text,
  add column if not exists category text default 'Territorio',
  add column if not exists badge text,
  add column if not exists badge_color text default 'default',
  add column if not exists image_type text,
  add column if not exists image_url text,
  add column if not exists source_url text,
  add column if not exists event_date timestamptz,
  add column if not exists published boolean default false,
  add column if not exists published_at timestamptz,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.posts
set published = coalesce(published, false)
where published is null;

update public.posts
set category = coalesce(nullif(trim(coalesce(category, '')), ''), 'Territorio'),
    badge_color = coalesce(nullif(trim(coalesce(badge_color, '')), ''), 'default'),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now()),
    published_at = case
      when published = true and published_at is null then coalesce(created_at, now())
      else published_at
    end
where category is null
   or trim(category) = ''
   or badge_color is null
   or trim(badge_color) = ''
   or created_at is null
   or updated_at is null
   or (published = true and published_at is null);

create index if not exists idx_posts_user_id
  on public.posts (user_id);

create index if not exists idx_posts_created_at
  on public.posts (created_at desc);

create index if not exists idx_posts_published_at
  on public.posts (published, published_at desc);

create index if not exists idx_posts_category
  on public.posts (category);

create unique index if not exists idx_posts_source_url
  on public.posts (source_url)
  where source_url is not null;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  badge_color text not null default 'default',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  legacy_aliases jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.categories
  add column if not exists name text,
  add column if not exists slug text,
  add column if not exists badge_color text default 'default',
  add column if not exists sort_order integer default 0,
  add column if not exists is_active boolean default true,
  add column if not exists legacy_aliases jsonb default '[]'::jsonb,
  add column if not exists created_at timestamptz default now();

update public.categories
set badge_color = coalesce(nullif(trim(coalesce(badge_color, '')), ''), 'default'),
    sort_order = coalesce(sort_order, 0),
    is_active = coalesce(is_active, true),
    legacy_aliases = coalesce(legacy_aliases, '[]'::jsonb),
    created_at = coalesce(created_at, now())
where badge_color is null
   or trim(badge_color) = ''
   or sort_order is null
   or is_active is null
   or legacy_aliases is null
   or created_at is null;

create unique index if not exists idx_categories_name_unique
  on public.categories (name);

create unique index if not exists idx_categories_slug_unique
  on public.categories (slug);

insert into public.categories (name, slug, badge_color, sort_order, legacy_aliases)
values
  ('Ambiente', 'ambiente', 'default', 10, '["territorio", "fauna", "ecoturismo"]'::jsonb),
  ('Anniversari', 'anniversari', 'green', 20, '[]'::jsonb),
  ('Assemblea', 'assemblea', 'default', 30, '[]'::jsonb),
  ('Canoa', 'canoa', 'green', 40, '[]'::jsonb),
  ('Ciclismo', 'ciclismo', 'default', 50, '[]'::jsonb),
  ('Festa del Pesce', 'festa-del-pesce', 'green', 60, '[]'::jsonb),
  ('Iniziative', 'iniziative', 'green', 70, '["eventi", "vita locale", "avvisi", "richieste", "storie", "il luccio", "storia"]'::jsonb),
  ('Love-luccio', 'love-luccio', 'green', 80, '[]'::jsonb),
  ('Mincio-art', 'mincio-art', 'default', 90, '[]'::jsonb),
  ('Natale', 'natale', 'green', 100, '[]'::jsonb),
  ('Rassegna Stampa', 'rassegna-stampa', 'default', 110, '[]'::jsonb),
  ('Tesseramento', 'tesseramento', 'default', 120, '[]'::jsonb),
  ('Video', 'video', 'default', 130, '[]'::jsonb)
on conflict (slug) do update
set name = excluded.name,
    badge_color = excluded.badge_color,
    sort_order = excluded.sort_order,
    legacy_aliases = excluded.legacy_aliases,
    is_active = true;

-- ------------------------------------------------------------------
-- Utility functions
-- ------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role = 'admin'
  );
$$;

create or replace function public.is_member(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role in ('user', 'admin')
  );
$$;

-- ------------------------------------------------------------------
-- Settings table
-- ------------------------------------------------------------------
create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  comment_privacy text not null default 'all' check (comment_privacy in ('all', 'members', 'none')),
  notif_frequency text not null default 'daily' check (notif_frequency in ('instant', 'daily', 'weekly', 'off')),
  notif_email boolean not null default false,
  preferred_categories jsonb not null default '[]'::jsonb,
  accessibility_fontsize text not null default 'md' check (accessibility_fontsize in ('sm', 'md', 'lg', 'xl')),
  accessibility_high_contrast boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_settings
  add column if not exists comment_privacy text default 'all',
  add column if not exists notif_frequency text default 'daily',
  add column if not exists notif_email boolean default false,
  add column if not exists preferred_categories jsonb default '[]'::jsonb,
  add column if not exists accessibility_fontsize text default 'md',
  add column if not exists accessibility_high_contrast boolean default false,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.user_settings
set comment_privacy = coalesce(nullif(trim(coalesce(comment_privacy, '')), ''), 'all'),
    notif_frequency = coalesce(nullif(trim(coalesce(notif_frequency, '')), ''), 'daily'),
    notif_email = coalesce(notif_email, false),
    preferred_categories = coalesce(preferred_categories, '[]'::jsonb),
    accessibility_fontsize = coalesce(nullif(trim(coalesce(accessibility_fontsize, '')), ''), 'md'),
    accessibility_high_contrast = coalesce(accessibility_high_contrast, false),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now())
where comment_privacy is null
   or notif_frequency is null
   or notif_email is null
   or preferred_categories is null
   or accessibility_fontsize is null
   or accessibility_high_contrast is null
   or created_at is null
   or updated_at is null;

-- ------------------------------------------------------------------
-- Toxic words dictionary
-- ------------------------------------------------------------------
create table if not exists public.blocked_words (
  word text primary key,
  created_at timestamptz not null default now()
);

insert into public.blocked_words(word)
values
  ('vaffanculo'),
  ('stronzo'),
  ('coglione'),
  ('merda'),
  ('idiota'),
  ('cretino'),
  ('troia'),
  ('puttana'),
  ('razzista'),
  ('violenza')
on conflict do nothing;

create or replace function public.contains_blocked_words(input_text text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.blocked_words b
    where lower(coalesce(input_text, '')) ~ ('(^|\\W)' || regexp_replace(lower(b.word), '([\\W])', '\\\\1', 'g') || '(\\W|$)')
  );
$$;

-- ------------------------------------------------------------------
-- Comments
-- ------------------------------------------------------------------
create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_username text,
  content text not null,
  is_hidden boolean not null default false,
  moderation_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.comments
  add column if not exists post_id uuid references public.posts(id) on delete cascade,
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists author_username text,
  add column if not exists content text,
  add column if not exists is_hidden boolean default false,
  add column if not exists moderation_note text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.comments
set is_hidden = coalesce(is_hidden, false),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now())
where is_hidden is null
   or created_at is null
   or updated_at is null;

create index if not exists idx_comments_post_id on public.comments(post_id);
create index if not exists idx_comments_user_id on public.comments(user_id);

create or replace function public.guard_comment_insert_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  links_count int;
begin
  if char_length(trim(coalesce(new.content, ''))) < 3 then
    raise exception 'Commento troppo breve';
  end if;

  if char_length(coalesce(new.content, '')) > 1200 then
    raise exception 'Commento troppo lungo';
  end if;

  select coalesce(count(*), 0) into links_count
  from regexp_matches(coalesce(new.content, ''), '(https?://|www\\.)', 'gi');

  if links_count > 2 then
    raise exception 'Troppi link nel commento';
  end if;

  if public.contains_blocked_words(new.content) then
    raise exception 'Il commento contiene parole non consentite';
  end if;

  return new;
end;
$$;

-- ------------------------------------------------------------------
-- Reports / moderation queue
-- ------------------------------------------------------------------
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  post_id uuid references public.posts(id) on delete cascade,
  comment_id uuid references public.comments(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  details text,
  status text not null default 'pending' check (status in ('pending', 'reviewing', 'resolved', 'rejected')),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint reports_target_check check (post_id is not null or comment_id is not null)
);

alter table public.reports
  add column if not exists post_id uuid references public.posts(id) on delete cascade,
  add column if not exists comment_id uuid references public.comments(id) on delete cascade,
  add column if not exists reporter_id uuid references auth.users(id) on delete cascade,
  add column if not exists reason text,
  add column if not exists details text,
  add column if not exists status text default 'pending',
  add column if not exists reviewed_by uuid references auth.users(id),
  add column if not exists reviewed_at timestamptz,
  add column if not exists created_at timestamptz default now();

update public.reports
set status = coalesce(nullif(trim(coalesce(status, '')), ''), 'pending'),
    created_at = coalesce(created_at, now())
where status is null
   or trim(status) = ''
   or created_at is null;

create index if not exists idx_reports_status on public.reports(status);
create index if not exists idx_reports_created_at on public.reports(created_at desc);
create unique index if not exists uq_reports_unique_per_user_target
  on public.reports(
    reporter_id,
    coalesce(post_id, '00000000-0000-0000-0000-000000000000'::uuid),
    coalesce(comment_id, '00000000-0000-0000-0000-000000000000'::uuid)
  );

-- ------------------------------------------------------------------
-- Post likes (single like per user/post)
-- ------------------------------------------------------------------
create table if not exists public.post_likes (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_username text,
  created_at timestamptz not null default now(),
  constraint post_likes_unique_per_user_post unique (post_id, user_id)
);

alter table public.post_likes
  add column if not exists post_id uuid references public.posts(id) on delete cascade,
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists actor_username text,
  add column if not exists created_at timestamptz default now();

update public.post_likes
set created_at = coalesce(created_at, now())
where created_at is null;

create index if not exists idx_post_likes_post_id on public.post_likes(post_id);
create index if not exists idx_post_likes_user_id on public.post_likes(user_id);
create index if not exists idx_post_likes_created_at on public.post_likes(created_at desc);

-- ------------------------------------------------------------------
-- Lightweight notifications for post authors
-- ------------------------------------------------------------------
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  actor_username text,
  post_id uuid not null references public.posts(id) on delete cascade,
  comment_id uuid references public.comments(id) on delete cascade,
  type text not null check (type in ('like', 'comment')),
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.notifications
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists actor_id uuid references auth.users(id) on delete set null,
  add column if not exists actor_username text,
  add column if not exists post_id uuid references public.posts(id) on delete cascade,
  add column if not exists comment_id uuid references public.comments(id) on delete cascade,
  add column if not exists type text,
  add column if not exists message text,
  add column if not exists is_read boolean default false,
  add column if not exists created_at timestamptz default now();

update public.notifications
set is_read = coalesce(is_read, false),
    created_at = coalesce(created_at, now())
where is_read is null
   or created_at is null;

create index if not exists idx_notifications_user_created on public.notifications(user_id, created_at desc);
create index if not exists idx_notifications_unread on public.notifications(user_id, is_read, created_at desc);

-- ------------------------------------------------------------------
-- Site telemetry
-- ------------------------------------------------------------------
create table if not exists public.site_stats (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table public.site_stats
  add column if not exists value text,
  add column if not exists updated_at timestamptz default now();

update public.site_stats
set updated_at = coalesce(updated_at, now())
where updated_at is null;

create table if not exists public.site_releases (
  id uuid primary key default gen_random_uuid(),
  version text not null,
  notes text,
  released_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

alter table public.site_releases
  add column if not exists version text,
  add column if not exists notes text,
  add column if not exists released_at timestamptz default now(),
  add column if not exists created_by uuid references auth.users(id);

update public.site_releases
set released_at = coalesce(released_at, now())
where released_at is null;

create index if not exists idx_site_releases_released_at on public.site_releases(released_at desc);

-- ------------------------------------------------------------------
-- Updated_at triggers
-- ------------------------------------------------------------------
drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists trg_posts_updated_at on public.posts;
create trigger trg_posts_updated_at
before update on public.posts
for each row execute function public.touch_updated_at();

drop trigger if exists trg_user_settings_updated_at on public.user_settings;
create trigger trg_user_settings_updated_at
before update on public.user_settings
for each row execute function public.touch_updated_at();

drop trigger if exists trg_comments_updated_at on public.comments;
create trigger trg_comments_updated_at
before update on public.comments
for each row execute function public.touch_updated_at();

drop trigger if exists trg_site_stats_updated_at on public.site_stats;
create trigger trg_site_stats_updated_at
before update on public.site_stats
for each row execute function public.touch_updated_at();

-- ------------------------------------------------------------------
-- Post guard (anti-spam + toxic words)
-- ------------------------------------------------------------------
create or replace function public.guard_post_insert_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  links_count int;
  full_text text;
begin
  full_text := concat_ws(E'\n', coalesce(new.title, ''), coalesce(new.excerpt, ''), coalesce(new.content, ''));

  if char_length(trim(coalesce(new.title, ''))) < 3 then
    raise exception 'Titolo troppo breve';
  end if;

  if char_length(trim(coalesce(new.content, ''))) < 10 then
    raise exception 'Contenuto troppo breve';
  end if;

  select coalesce(count(*), 0) into links_count
  from regexp_matches(full_text, '(https?://|www\\.)', 'gi');

  if links_count > 8 then
    raise exception 'Troppi link nel post';
  end if;

  if public.contains_blocked_words(full_text) then
    raise exception 'Il post contiene parole non consentite';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_guard_posts on public.posts;
create trigger trg_guard_posts
before insert or update on public.posts
for each row execute function public.guard_post_insert_update();

drop trigger if exists trg_guard_comments on public.comments;
create trigger trg_guard_comments
before insert or update on public.comments
for each row execute function public.guard_comment_insert_update();

-- ------------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.categories enable row level security;
alter table public.user_settings enable row level security;
alter table public.blocked_words enable row level security;
alter table public.comments enable row level security;
alter table public.reports enable row level security;
alter table public.post_likes enable row level security;
alter table public.notifications enable row level security;
alter table public.site_stats enable row level security;
alter table public.site_releases enable row level security;

-- Profiles
drop policy if exists profiles_public_read on public.profiles;
create policy profiles_public_read on public.profiles
for select using (true);

drop policy if exists profiles_owner_insert on public.profiles;
create policy profiles_owner_insert on public.profiles
for insert with check (auth.uid() = id);

drop policy if exists profiles_owner_update on public.profiles;
create policy profiles_owner_update on public.profiles
for update using (auth.uid() = id or public.is_admin(auth.uid()))
with check (auth.uid() = id or public.is_admin(auth.uid()));

-- Posts
drop policy if exists posts_public_read on public.posts;
create policy posts_public_read on public.posts
for select using (
  published = true
  or auth.uid() = user_id
  or public.is_admin(auth.uid())
);

drop policy if exists posts_owner_insert on public.posts;
create policy posts_owner_insert on public.posts
for insert with check (
  auth.uid() = user_id
  and public.is_member(auth.uid())
);

drop policy if exists posts_owner_update on public.posts;
create policy posts_owner_update on public.posts
for update using (auth.uid() = user_id or public.is_admin(auth.uid()))
with check (auth.uid() = user_id or public.is_admin(auth.uid()));

drop policy if exists posts_owner_delete on public.posts;
create policy posts_owner_delete on public.posts
for delete using (auth.uid() = user_id or public.is_admin(auth.uid()));

-- Categories
drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories
for select using (is_active = true or public.is_admin(auth.uid()));

drop policy if exists categories_admin_write on public.categories;
create policy categories_admin_write on public.categories
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- User settings
drop policy if exists user_settings_owner_read on public.user_settings;
create policy user_settings_owner_read on public.user_settings
for select using (auth.uid() = user_id or public.is_admin(auth.uid()));

drop policy if exists user_settings_owner_insert on public.user_settings;
create policy user_settings_owner_insert on public.user_settings
for insert with check (auth.uid() = user_id);

drop policy if exists user_settings_owner_update on public.user_settings;
create policy user_settings_owner_update on public.user_settings
for update using (auth.uid() = user_id or public.is_admin(auth.uid()))
with check (auth.uid() = user_id or public.is_admin(auth.uid()));

drop policy if exists user_settings_owner_delete on public.user_settings;
create policy user_settings_owner_delete on public.user_settings
for delete using (auth.uid() = user_id or public.is_admin(auth.uid()));

-- Blocked words
drop policy if exists blocked_words_admin_write on public.blocked_words;
create policy blocked_words_admin_write on public.blocked_words
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- Comments
drop policy if exists comments_public_read on public.comments;
create policy comments_public_read on public.comments
for select using (
  is_hidden = false
  or auth.uid() = user_id
  or public.is_admin(auth.uid())
);

drop policy if exists comments_member_insert on public.comments;
create policy comments_member_insert on public.comments
for insert with check (
  auth.uid() = user_id
  and public.is_member(auth.uid())
);

drop policy if exists comments_owner_update_short_window on public.comments;
create policy comments_owner_update_short_window on public.comments
for update using (
  auth.uid() = user_id
  and created_at > now() - interval '10 minutes'
)
with check (
  auth.uid() = user_id
  and created_at > now() - interval '10 minutes'
);

drop policy if exists comments_owner_or_admin_delete on public.comments;
create policy comments_owner_or_admin_delete on public.comments
for delete using (auth.uid() = user_id or public.is_admin(auth.uid()));

-- Reports
drop policy if exists reports_admin_read on public.reports;
create policy reports_admin_read on public.reports
for select using (public.is_admin(auth.uid()));

drop policy if exists reports_user_insert on public.reports;
create policy reports_user_insert on public.reports
for insert with check (auth.uid() = reporter_id);

drop policy if exists reports_admin_update on public.reports;
create policy reports_admin_update on public.reports
for update using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists reports_admin_delete on public.reports;
create policy reports_admin_delete on public.reports
for delete using (public.is_admin(auth.uid()));

-- Post likes
drop policy if exists post_likes_public_read on public.post_likes;
create policy post_likes_public_read on public.post_likes
for select using (true);

drop policy if exists post_likes_member_insert on public.post_likes;
create policy post_likes_member_insert on public.post_likes
for insert with check (
  auth.uid() = user_id
  and public.is_member(auth.uid())
);

drop policy if exists post_likes_owner_or_admin_delete on public.post_likes;
create policy post_likes_owner_or_admin_delete on public.post_likes
for delete using (
  auth.uid() = user_id
  or public.is_admin(auth.uid())
);

-- Notifications
drop policy if exists notifications_owner_or_admin_read on public.notifications;
create policy notifications_owner_or_admin_read on public.notifications
for select using (
  auth.uid() = user_id
  or public.is_admin(auth.uid())
);

drop policy if exists notifications_actor_insert on public.notifications;
create policy notifications_actor_insert on public.notifications
for insert with check (
  auth.uid() = actor_id
  and auth.uid() <> user_id
  and public.is_member(auth.uid())
);

drop policy if exists notifications_owner_or_admin_update on public.notifications;
create policy notifications_owner_or_admin_update on public.notifications
for update using (
  auth.uid() = user_id
  or public.is_admin(auth.uid())
)
with check (
  auth.uid() = user_id
  or public.is_admin(auth.uid())
);

drop policy if exists notifications_owner_or_admin_delete on public.notifications;
create policy notifications_owner_or_admin_delete on public.notifications
for delete using (
  auth.uid() = user_id
  or public.is_admin(auth.uid())
);

-- Site stats
drop policy if exists site_stats_public_read on public.site_stats;
create policy site_stats_public_read on public.site_stats
for select using (true);

drop policy if exists site_stats_admin_write on public.site_stats;
create policy site_stats_admin_write on public.site_stats
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- Site releases
drop policy if exists site_releases_public_read on public.site_releases;
create policy site_releases_public_read on public.site_releases
for select using (true);

drop policy if exists site_releases_admin_write on public.site_releases;
create policy site_releases_admin_write on public.site_releases
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- ------------------------------------------------------------------
-- Grants for Supabase API roles
-- ------------------------------------------------------------------
grant usage on schema public to anon, authenticated, service_role;

grant select on table
  public.profiles,
  public.posts,
  public.categories,
  public.comments,
  public.post_likes,
  public.site_stats,
  public.site_releases
to anon;

grant select, insert, update, delete on table
  public.profiles,
  public.posts,
  public.categories,
  public.user_settings,
  public.blocked_words,
  public.comments,
  public.reports,
  public.post_likes,
  public.notifications,
  public.site_stats,
  public.site_releases
to authenticated, service_role;

grant usage, select on all sequences in schema public to authenticated, service_role;
grant execute on function public.is_admin(uuid) to anon, authenticated, service_role;
grant execute on function public.is_member(uuid) to anon, authenticated, service_role;
grant execute on function public.contains_blocked_words(text) to anon, authenticated, service_role;